### ISSUE TITLE
Полный вариант ЛР + префиксно-суффиксные грамматики

### ISSUE THREAD

**Issue by TonitaN** [affeeal/iu9-tfl-lab3#1]
Ожидается активность @geogreck по теме этой разработки.

**Comment by geogreck** [comment]
Прогноз погоды нередко оказывается ошибочным..

**Comment by TonitaN** [comment]
А как же те 600 строк в cfg.rs? 👀 И функция niam? Всё тлен?

**Comment by geogreck** [comment]
На процессе интеграции и сборки полной лабораторной работы возникли технические сложности из-за которых задумываешься, не проще ли сделать какую-нибудь 5 лабу(особенно соло вариант). Но эту лабу я пока что не бросаю

**Comment by TonitaN** [comment]
Написать 600 строк кода и бросить - это как-то слишком в стиле Банникова. Не надо, а то сами не заметите, как окажетесь на практике в Переславле.

**Comment by uma-op** [comment]
600 строк звучит маловато. Я бы предложил бросать, когда количество дойдет хотя бы до 1000

**Comment by TonitaN** [comment]
Может, и 1000 - на виду ведь только верхушка айсберга... Если даже я не вижу ни одного коммита, это не значит, что не написано ни одной строки. ("по второй лабораторной почти ничего нет"(с) известно-кто )

**Comment by TonitaN** [comment]
@geogreck , какие проблемы у вас возникли на этапе интеграции? По пунктам перечислите, и я попробую дать внятные советы, как их решить. Психологические проблемы не предлагать.

**Comment by geogreck** [comment]
Возникли проблемы с необходимостью посещения аттестационной комиссии по базам данных. А если серьезно, то просто слишком много долгов и закрыть всё не особо успевается.

**Comment by TonitaN** [comment]
Да видела я эту комиссию по БД. Ничем она не отличается от обычной пересдачи, кроме градуса комментариев ИЭ. Если не сбегать с наполовину написанным билетом, не расстреляют.

P.S. - Технически, комиссия по тфя будет в марте. У меня и без вас на неё пойдёт толпа, поэтому вы погоды не испортите. Неужели и до марта совсем нет времени? Ну если так, то хотя бы третью лр доделайте, и на следующий год по лабам будет перезачёт. За сим вопрос про технические сложности остаётся открытым.
